<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE declaraciones [
 <!ELEMENT declaraciones (consonante*, variable*)>
 <!ELEMENT consonante (#PCDATA)>
 <!ATTLIST consonante valor CDATA #REQUIRED>
 <!ELEMENT variable (#PCDATA)>
 <!ATTLIST variable tipo CDATA #IMPLIED>
]>
<declaraciones>
 <consonante valor="3.141592">PI</consonante>
 <variable tipo="real">radio</variable>
 <variable>area</variable>
 <variable>longitud</variable>
</declaraciones>

<!--  

El siguiente documento XML no es válido, modificalo, lo mínimo posible, para
que lo sea. Modifica la DTD solo.

a) declaraciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE declaraciones [
 <!ELEMENT declaraciones (consonante | tipo | variable)>
 <!ELEMENT consonante (#PCDATA)>
 <!ATTLIST consonante valor CDATA #REQUIRED>
 <!ELEMENT tipo (#PCDATA)>
 <!ELEMENT variable (#PCDATA)>
 <!ATTLIST variable tipo CDATA #REQUIRED>
]>
<declaraciones>
 <consonante valor="3.141592">PI</consonante>
 <variable tipo="real">radio</variable>
 <variable>area</variable>
 <variable>longitud</variable>
</declaraciones>

-->
